In [1]:
import pandas as pd
import os
import sys
# Agregar el directorio principal al sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from utils.generar_enfrent import generar_enfrentamientos
from utils.vuelta_grupos import vuelta_gr
from utils.df_enfrentamientos import df_ida_o_vuelta
from utils.enfrentamientos_sinVS import df_partidos
from utils.descomp_tupla_columnas import descomponer_tupla

 #* Ruta a la carpeta 'data'
carpeta = 'data'

In [2]:
def partidos_jornadas(df_partidos, num_jornada, col_local, col_visitante, col_rtdo_local, col_rtdo_visitante):
    df_partidos_jornada = pd.DataFrame()
    #* Aplicando la función a la columna 'datos' y creando nuevas columnas
    df_partidos_jornada[[col_local, col_visitante]] = df_partidos[f'Jornada {num_jornada}'].apply(descomponer_tupla) #* Usamos la función apply() para aplicar una función a una columna de un dataframe
    df_partidos_jornada[col_rtdo_visitante] = 0
    df_partidos_jornada.insert(0, col_rtdo_local, 0)
    
    return df_partidos_jornada

In [3]:
df_grupos = pd.read_excel('data/sorteo_grupos.xlsx')
grupo_A = list(df_grupos['Grupo A'])
grupo_B = list(df_grupos['Grupo B'])

In [4]:
 #* GRUPO A:
ida_grA = generar_enfrentamientos(grupo_A) #* Generar partidos de ida
vuelta_grA = vuelta_gr(ida_grA) #* Generar partidos de vuelta
df_ida_grA = df_ida_o_vuelta(ida_grA)  #* Generar DF de los partidos de ida
df_vuelta_grA = df_ida_o_vuelta(vuelta_grA, 6) #* El 6 indica el inicio de la jornada de los partidos de vuelta
idx_grA = 'GRUPO A'
calendario_grA = pd.concat([df_ida_grA, df_vuelta_grA], axis = 1) #* Crear dataframe con todos los partidos de ida y vuelta gr1
calendario_grA['GRUPO'] = idx_grA
calendario_grA.set_index('GRUPO', drop=True, append=False, inplace=True) #* Cambiar el indice del DF para distinguir los grupos al juntarlos
#calendario_grA #* Usar para VISUALIZAR LOS PARTIDOS DE IDA Y VUELTA DEL GRUPO 1

#* GRUPO B:
ida_grB = generar_enfrentamientos(grupo_B) #* Generar partidos de ida
vuelta_grB = vuelta_gr(ida_grB) #* Generar partidos de vuelta
df_ida_grB = df_ida_o_vuelta(ida_grB)  #* Generar DF de los partidos de ida
df_vuelta_grB = df_ida_o_vuelta(vuelta_grB, 6) #* El 6 indica el inicio de la jornada de los partidos de vuelta
idx_grB = 'GRUPO B'
calendario_grB = pd.concat([df_ida_grB, df_vuelta_grB], axis = 1) #* Crear dataframe con todos los partidos de ida y vuelta gr2
calendario_grB['GRUPO'] = idx_grB
calendario_grB.set_index('GRUPO', drop=True, append=False, inplace=True) #* Cambiar el indice del DF para distinguir los grupos al juntarlos
#calendario_grB #* Usar para VISUALIZAR LOS PARTIDOS DE IDA Y VUELTA DEL GRUPO 2

In [5]:
calendario_grA

,Jornada 1,Jornada 2,Jornada 3,Jornada 4,Jornada 5,Jornada 6,Jornada 7,Jornada 8,Jornada 9,Jornada 10
GRUPO,,,,,,,,,,
GRUPO A,Ruso VS Lope,Ruso VS Papu,Ruso VS Tony,Ruso VS Kero,Ruso VS Fale,Lope VS Ruso,Papu VS Ruso,Tony VS Ruso,Kero VS Ruso,Fale VS Ruso
GRUPO A,Fale VS Papu,Lope VS Tony,Papu VS Kero,Tony VS Fale,Kero VS Lope,Papu VS Fale,Tony VS Lope,Kero VS Papu,Fale VS Tony,Lope VS Kero
GRUPO A,Kero VS Tony,Fale VS Kero,Lope VS Fale,Papu VS Lope,Tony VS Papu,Tony VS Kero,Kero VS Fale,Fale VS Lope,Lope VS Papu,Papu VS Tony

In [6]:
 #! JORNADAS DE IFA SIN FORMATO PARA GENERAR  CADA JORNADA
ida_gA = df_partidos(ida_grA)
ida_gB = df_partidos(ida_grB)

In [7]:
ida_gB

,Jornada 1,Jornada 2,Jornada 3,Jornada 4,Jornada 5
0,"(Puche, Palop)","(Puche, Gonzo)","(Puche, Armada)","(Puche, Coquina)","(Puche, Kike)"
1,"(Kike, Gonzo)","(Palop, Armada)","(Gonzo, Coquina)","(Armada, Kike)","(Coquina, Palop)"
2,"(Coquina, Armada)","(Kike, Coquina)","(Palop, Kike)","(Gonzo, Palop)","(Armada, Gonzo)"

## JORNADA ACTUAL -> CAMBIAR DESDE AQUI LO ANTERIOR NO SE MODIFICA:

In [17]:

#! PARTIDOS DE LA JORNADA 1:
j1_gA = ida_gA
j1_gB = ida_gB['Jornada 1']
grA_jor1 = partidos_jornadas(ida_gA, 1, 'LOCAL', 'VISITANTE', 'RTDO L', 'RTDO V')
grB_jor1 = partidos_jornadas(ida_gB, 2, 'LOCAL.1', 'VISITANTE.1', 'RTDO L.1', 'RTDO V.1')
vacio = pd.DataFrame()
vacio['Jornada'] = ['JOR. 1'] * 3
df_jornada_actual1  = pd.concat([grA_jor1, vacio, grB_jor1], axis = 1)
df_jornada_actual1

,RTDO L,LOCAL,VISITANTE,RTDO V,Jornada,RTDO L.1,LOCAL.1,VISITANTE.1,RTDO V.1
0,0,Ruso,Lope,0,JOR. 1,0,Puche,Gonzo,0
1,0,Fale,Papu,0,JOR. 1,0,Palop,Armada,0
2,0,Kero,Tony,0,JOR. 1,0,Kike,Coquina,0

In [ ]:
ruta_archivo = os.path.join(carpeta, 'jornada_1_inicial.xlsx')
df_jornada_actual1.to_excel(ruta_archivo, index=False)

## PARTIDOS DE LA VUELTA A PARTIR DE LA JORNADA 6 (JORNADA ACTUAL)

In [12]:
# Tomar solo los partidos de la "Jornada actual"
jornada10 = df_vuelta_grA['Jornada 6']
# Separar "Local" y "Visitante" dividiendo la cadena por ' VS '
jornada10_split = jornada10.str.split(' VS ', expand=True)
jornada10_split.columns = ['LOCAL', 'VISITANTE']
jornada10
# Crear el nuevo DataFrame con el formato deseado
jornada_actual = pd.DataFrame({
    'RTDO L': [0] * len(jornada10_split),  # Columna de resultados locales (inicialmente en 0)
    'LOCAL': jornada10_split['LOCAL'],     # Columna de equipos locales
    'VISITANTE': jornada10_split['VISITANTE'],  # Columna de equipos visitantes
    'RTDO V': [0] * len(jornada10_split),  # Columna de resultados visitantes (inicialmente en 0)
    'jornada': ['JOR. 6'] * len(jornada10_split),  # Columna de la jornada (aquí es "JOR. 1")
    # Columnas adicionales para un segundo grupo de partidos
    'RTDO L.1': [0] * len(jornada10_split),
    'LOCAL.1': ['Kike', 'Coquina', 'Armada'],  #! Ejemplo de equipos adicionales (puedes cambiarlos) BASARSE EN EL ORDEN DEL CALEND GENERAL
    'VISITANTE.1': ['Puche', 'Papu' ,'Gonzo'],  # Ejemplo de visitantes adicionales
    'RTDO V.1': [0] * len(jornada10_split)
})

jornada_actual

,RTDO L,LOCAL,VISITANTE,RTDO V,jornada,RTDO L.1,LOCAL.1,VISITANTE.1,RTDO V.1
0,0,Lope,Ruso,0,JOR. 6,0,Kike,Puche,0
1,0,Papu,Fale,0,JOR. 6,0,Coquina,Papu,0
2,0,Tony,Kero,0,JOR. 6,0,Armada,Gonzo,0

In [7]:
ruta_archivo = os.path.join(carpeta, 'jornada_10_inicial.xlsx')
jornada_actual.to_excel(ruta_archivo, index=False)