In [6]:
import pandas as pd
import os
from utils.generar_enfrent import generar_enfrentamientos
from utils.vuelta_grupos import vuelta_gr
from utils.df_enfrentamientos import df_ida_o_vuelta
from utils.enfrentamientos_sinVS import df_partidos
#from utils.partidos_jornadas import partidos_jornadas

In [4]:
df_grupos = pd.read_excel('sorteo_grupos.xlsx')
grupo_A = list(df_grupos['Grupo A'])
grupo_B = list(df_grupos['Grupo B'])

In [7]:
 #* Ruta a la carpeta 'data'
carpeta = 'data'

In [6]:
 #* Verificar si la carpeta existe, y si no, crearla
if not os.path.exists(carpeta):
    os.makedirs(carpeta)

### **GRUPOS**

In [1]:
 #* GRUPO A:
ida_grA = generar_enfrentamientos(grupo_A) #* Generar partidos de ida
vuelta_grA = vuelta_gr(ida_grA) #* Generar partidos de vuelta
df_ida_grA = df_ida_o_vuelta(ida_grA)  #* Generar DF de los partidos de ida
df_vuelta_grA = df_ida_o_vuelta(vuelta_grA, 6) #* El 6 indica el inicio de la jornada de los partidos de vuelta
idx_grA = 'GRUPO A'
calendario_grA = pd.concat([df_ida_grA, df_vuelta_grA], axis = 1) #* Crear dataframe con todos los partidos de ida y vuelta gr1
calendario_grA['GRUPO'] = idx_grA
calendario_grA.set_index('GRUPO', drop=True, append=False, inplace=True) #* Cambiar el indice del DF para distinguir los grupos al juntarlos
#calendario_grA #* Usar para VISUALIZAR LOS PARTIDOS DE IDA Y VUELTA DEL GRUPO 1

#* GRUPO B:
ida_grB = generar_enfrentamientos(grupo_B) #* Generar partidos de ida
vuelta_grB = vuelta_gr(ida_grB) #* Generar partidos de vuelta
df_ida_grB = df_ida_o_vuelta(ida_grB)  #* Generar DF de los partidos de ida
df_vuelta_grB = df_ida_o_vuelta(vuelta_grB, 6) #* El 6 indica el inicio de la jornada de los partidos de vuelta
idx_grB = 'GRUPO B'
calendario_grB = pd.concat([df_ida_grB, df_vuelta_grB], axis = 1) #* Crear dataframe con todos los partidos de ida y vuelta gr2
calendario_grB['GRUPO'] = idx_grB
calendario_grB.set_index('GRUPO', drop=True, append=False, inplace=True) #* Cambiar el indice del DF para distinguir los grupos al juntarlos
#calendario_grB #* Usar para VISUALIZAR LOS PARTIDOS DE IDA Y VUELTA DEL GRUPO 2

NameError: name 'generar_enfrentamientos' is not defined

### **CALENDARIOS**

In [8]:
calendario_grupos = pd.concat([calendario_grA, calendario_grB], axis = 0)
calendario_grupos

,Jornada 1,Jornada 2,Jornada 3,Jornada 4,Jornada 5,Jornada 6,Jornada 7,Jornada 8,Jornada 9,Jornada 10
GRUPO,,,,,,,,,,
GRUPO A,Palop VS Lope,Palop VS Fale,Palop VS Ruso,Palop VS Tony,Palop VS Kero,Lope VS Palop,Fale VS Palop,Ruso VS Palop,Tony VS Palop,Kero VS Palop
GRUPO A,Kero VS Fale,Lope VS Ruso,Fale VS Tony,Ruso VS Kero,Tony VS Lope,Fale VS Kero,Ruso VS Lope,Tony VS Fale,Kero VS Ruso,Lope VS Tony
GRUPO A,Tony VS Ruso,Kero VS Tony,Lope VS Kero,Fale VS Lope,Ruso VS Fale,Ruso VS Tony,Tony VS Kero,Kero VS Lope,Lope VS Fale,Fale VS Ruso
GRUPO B,Diego VS Coquina,Diego VS Armada,Diego VS Gonzo,Diego VS Papu,Diego VS Kike,Coquina VS Diego,Armada VS Diego,Gonzo VS Diego,Papu VS Diego,Kike VS Diego
GRUPO B,Kike VS Armada,Coquina VS Gonzo,Armada VS Papu,Gonzo VS Kike,Papu VS Coquina,Armada VS Kike,Gonzo VS Coquina,Papu VS Armada,Kike VS Gonzo,Coquina VS Papu
GRUPO B,Papu VS Gonzo,Kike VS Papu,Coquina VS Kike,Armada VS Coquina,Gonzo VS Armada,Gonzo VS Papu,Papu VS Kike,Kike VS Coquina,Coquina VS Armada,Armada VS Gonzo

In [9]:

#* Guardar el DataFrame en un archivo Excel en la carpeta 'data'
#ruta_archivo = os.path.join(carpeta, 'calendario_grupos.xlsx')
#calendario_grupos.to_excel(ruta_archivo, index=False)

# JORNADAS DE IDA

In [4]:
from utils.descomp_tupla_columnas import descomponer_tupla

def partidos_jornadas(df_partidos, num_jornada, col_local, col_visitante, col_rtdo_local, col_rtdo_visitante):
    df_partidos_jornada = pd.DataFrame()
    #* Aplicando la función a la columna 'datos' y creando nuevas columnas
    df_partidos_jornada[[col_local, col_visitante]] = df_partidos[f'Jornada {num_jornada}'].apply(descomponer_tupla) #* Usamos la función apply() para aplicar una función a una columna de un dataframe
    df_partidos_jornada[col_rtdo_visitante] = 0
    df_partidos_jornada.insert(0, col_rtdo_local, 0)
    
    return df_partidos_jornada

In [5]:
 #! JORNADAS DE IFA SIN FORMATO PARA GENERAR  CADA JORNADA
ida_gA = df_partidos(ida_grA)
ida_gB = df_partidos(ida_grB)

NameError: name 'df_partidos' is not defined

### JORNADA 1

In [12]:
 #! PARTIDOS DE LA JORNADA 1:
grA_jor1 = partidos_jornadas(ida_gA, 1, 'LOCAL', 'VISITANTE', 'RTDO_L', 'RTDO_VISITANTE')
grB_jor1 = partidos_jornadas(ida_gB, 1, 'LOCAL.1', 'VISITANTE.1', 'RTDO_L.1', 'RTDO_V.1')
vacio = pd.DataFrame()
vacio['jornada'] = ['JOR. 1'] * 3
df_jornada_actual  = pd.concat([grA_jor1, vacio, grB_jor1], axis = 1)
df_jornada_actual

,RTDO_L,LOCAL,VISITANTE,RTDO_VISITANTE,jornada,RTDO_L.1,LOCAL.1,VISITANTE.1,RTDO_V.1
0,0,Palop,Lope,0,JOR. 1,0,Diego,Coquina,0
1,0,Kero,Fale,0,JOR. 1,0,Kike,Armada,0
2,0,Tony,Ruso,0,JOR. 1,0,Papu,Gonzo,0

In [13]:
df_jornada_actual
# Guardar el DataFrame en un archivo Excel en la carpeta 'data'
#ruta_archivo = os.path.join(carpeta, 'jornada_1_inicial.xlsx')
#df_jornada_actual.to_excel(ruta_archivo, index=False)

,RTDO_L,LOCAL,VISITANTE,RTDO_VISITANTE,jornada,RTDO_L.1,LOCAL.1,VISITANTE.1,RTDO_V.1
0,0,Palop,Lope,0,JOR. 1,0,Diego,Coquina,0
1,0,Kero,Fale,0,JOR. 1,0,Kike,Armada,0
2,0,Tony,Ruso,0,JOR. 1,0,Papu,Gonzo,0

### JORNADA 2

In [14]:
 #! PARTIDOS DE LA JORNADA 2:
j2_gA = ida_gA
j2_gB = ida_gB['Jornada 2']
grA_jor2 = partidos_jornadas(ida_gA, 2, 'LOCAL', 'VISITANTE', 'RTDO L', 'RTDO V')
grB_jor2 = partidos_jornadas(ida_gB, 2, 'LOCAL.1', 'VISITANTE.1', 'RTDO L.1', 'RTDO V.1')
vacio = pd.DataFrame()
vacio['Jornada'] = ['JOR. 2'] * 3
df_jornada_actual2  = pd.concat([grA_jor2, vacio, grB_jor2], axis = 1)
df_jornada_actual2

,RTDO L,LOCAL,VISITANTE,RTDO V,Jornada,RTDO L.1,LOCAL.1,VISITANTE.1,RTDO V.1
0,0,Palop,Fale,0,JOR. 2,0,Diego,Armada,0
1,0,Lope,Ruso,0,JOR. 2,0,Coquina,Gonzo,0
2,0,Kero,Tony,0,JOR. 2,0,Kike,Papu,0

In [15]:
#ruta_archivo = os.path.join(carpeta, 'jornada_2_inicial.xlsx')
#df_jornada_actual2.to_excel(ruta_archivo, index=False)

JORNADA 3

In [18]:
 #! PARTIDOS DE LA JORNADA 3:
j3_gA = ida_gA
j3_gB = ida_gB['Jornada 3']
grA_jor3 = partidos_jornadas(ida_gA, 3, 'LOCAL', 'VISITANTE', 'RTDO L', 'RTDO V')
grB_jor3 = partidos_jornadas(ida_gB, 3, 'LOCAL.1', 'VISITANTE.1', 'RTDO L.1', 'RTDO V.1')
vacio = pd.DataFrame()
vacio['Jornada'] = ['JOR. 3'] * 3
df_jornada_actual3  = pd.concat([grA_jor3, vacio, grB_jor3], axis = 1)
df_jornada_actual3

,RTDO L,LOCAL,VISITANTE,RTDO V,Jornada,RTDO L.1,LOCAL.1,VISITANTE.1,RTDO V.1
0,0,Palop,Ruso,0,JOR. 3,0,Diego,Gonzo,0
1,0,Fale,Tony,0,JOR. 3,0,Armada,Papu,0
2,0,Lope,Kero,0,JOR. 3,0,Coquina,Kike,0

In [19]:
ruta_archivo = os.path.join(carpeta, 'jornada_3_inicial.xlsx')
df_jornada_actual3.to_excel(ruta_archivo, index=False)

In [2]:
 #! PARTIDOS DE LA JORNADA 4:
j4_gA = ida_gA
j4_gB = ida_gB['Jornada 4']
grA_jor4 = partidos_jornadas(ida_gA, 4, 'LOCAL', 'VISITANTE', 'RTDO L', 'RTDO V')
grB_jor4 = partidos_jornadas(ida_gB, 4, 'LOCAL.1', 'VISITANTE.1', 'RTDO L.1', 'RTDO V.1')
vacio = pd.DataFrame()
vacio['Jornada'] = ['JOR. 4'] * 3
df_jornada_actual4  = pd.concat([grA_jor4, vacio, grB_jor3], axis = 1)
df_jornada_actual4

NameError: name 'ida_gA' is not defined